package.list <-
  c("abind", "acepack", "ada", "ade4", "ADGofTest", "AER", "agricolae", 
    "akima", "AlgDesign", "animation", "ape", "aplpack", "AquaEnv", 
    "aroma.affymetrix", "aroma.apd", "aroma.core", "asbio", "ash", 
    "base", "base64", "base64enc", "bbmle", "BCE", "bdsmatrix", "biglm", 
    "BiocGenerics", "BiocInstaller", "Biostrings", "bit", "bitops", 
    "boot", "bootstrap", "BsMD", "Cairo", "cairoDevice", "candisc", 
    "car", "caret", "caTools", "chron", "CITAN", "class", "clue", 
    "cluster", "clusterGeneration", "clusterSim", "coda", "codetools", 
    "coin", "colorspace", "compiler", "conf.design", "corpcor", "crantastic", 
    "cubature", "DAAG", "data.table", "datasets", "date", "DBI", 
    "degreenet", "DEoptim", "deSolve", "devtools", "dichromat", "digest", 
    "directlabels", "DoE.base", "doMC", "dplyr", "dummies", "dynlm", 
    "e1071", "Ecdat", "effects", "ellipse", "emdbook", "ergm", "evaluate", 
    "extrafont", "extrafontdb", "fBasics", "fdrtool", "fEcofin", 
    "ff", "ffbase", "fields", "flexmix", "flux", "foreach", "foreign", 
    "formatR", "Formula", "FrF2", "fts", "gam", "gclus", "gdata", 
    "gee", "GeneNet", "geoPlot", "GGally", "ggplot2", "ggsubplot", 
    "gmp", "gnumeric", "googleVis", "gplots", "graphics", "grDevices", 
    "grid", "gridExtra", "grouped", "gsubfn", "gtable", "gtools", 
    "gWidgets", "gWidgetsRGtk2", "hash", "hbim", "hdrcde", "heplots", 
    "hexbin", "hglm", "highlight", "Hmisc", "HSAUR", "httr", "igraph", 
    "igraph0", "imguR", "ineq", "ipred", "IRanges", "iterators", 
    "itertools", "its", "JavaGD", "kernlab", "KernSmooth", "klaR", 
    "knitr", "ks", "labeling", "lasso2", "latentnet", "lattice", 
    "latticeExtra", "lda", "leaps", "limSolve", "lme4", "lmtest", 
    "locfit", "logspline", "longitudinal", "lpSolve", "lubridate", 
    "mapproj", "maps", "maptools", "markdown", "MASS", "Matrix", 
    "matrixcalc", "matrixStats", "maxLik", "mboost", "mclust", "MCMCpack", 
    "memoise", "MEMSS", "methods", "mgcv", "mice", "minpack.lm", 
    "misc3d", "miscTools", "mitools", "mix", "mlbench", "mlmRev", 
    "mlogit", "modeest", "modeltools", "moments", "msm", "multcomp", 
    "multicore", "munsell", "mutatr", "mvtnorm", "network", "networkDynamic", 
    "nlme", "NMOF", "nnet", "np", "numDeriv", "nws", "oce", "odfWeave", 
    "odfWeave.survey", "OrgMassSpecR", "oz", "parallel", "parser", 
    "party", "Peaks", "permute", "pixmap", "plm", "plotrix", "plyr", 
    "pmml", "png", "polyapost", "popbio", "POT", "prodlim", "proto", 
    "proxy", "PSCBS", "pscl", "pso", "quadprog", "quantreg", "R.cache", 
    "R.devices", "R.filesets", "R.huge", "R.methodsS3", "R.oo", "R.rsp", 
    "R.utils", "R2HTML", "RandForestGUI", "randomForest", "rattle", 
    "rbenchmark", "rcdd", "Rcmdr", "RColorBrewer", "Rcpp", "RCurl", 
    "relimp", "reporttools", "reshape", "reshape2", "rfPermute", 
    "rgenoud", "rggobi", "rgl", "Rglpk", "RGoogleDocs", "RgoogleMaps", 
    "RGraphics", "RGtk2", "rJava", "rjson", "RJSONIO", "rlecuyer", 
    "rmeta", "Rmpfr", "Rmpi", "robustbase", "ROCR", "RODBC", "rpart", 
    "RSQLite", "RSQLite.extfuns", "Rttf2pt1", "RUnit", "rworldmap", 
    "sampleSelection", "sandwich", "scales", "scatterplot3d", "schoolmath", 
    "sciplot", "sem", "sendmailR", "sensitivity", "seqinr", "sfsmisc", 
    "shapes", "simecol", "simPopulation", "sisus", "slam", "slidify", 
    "slidifyLibraries", "sm", "sna", "snow", "snowFT", "sp", "spam", 
    "sparkTable", "SparseM", "spatial", "spatialkernel", "splines", 
    "sqldf", "stabledist", "StatMatch", "statmod", "statnet", "stats", 
    "stats4", "stringr", "strucchange", "subselect", "survey", "survival", 
    "svmpath", "systemfit", "tabplot", "tcltk", "tcltk2", "TeachingDemos", 
    "testthat", "timeDate", "timeSeries", "tis", "tkrplot", "tm", 
    "tools", "topicmodels", "TRAMPR", "tree", "tripack", "truncreg", 
    "trust", "TSA", "tseries", "tweedie", "urca", "utils", "varSelRF", 
    "vcd", "vegan", "vegetarian", "VGAM", "VIM", "waveslim", "whisker", 
    "wordcloud", "XML", "xtable", "xts", "yaml", "Zelig", "zoo", 
    "manipulate", "rstudio")


sapply(package.list, install.packages)